const mockData = [
    {   id: 1, 
        image: 'https://picsum.photos/id/493/800/600',
        title: 'Product 1',
        description: 'We focus on ergonomics and meeting you where you work. It\'s only a keystroke away.',
        date: '22 April 2021',
        comments: '10',
        price: 20.90 },
    {   id: 2, 
        image: 'https://picsum.photos/id/494/800/600',
        title: 'Product 2',
        description: 'We focus on ergonomics and meeting you where you work. It\'s only a keystroke away.',
        date: '22 April 2021',
        comments: '10',
        price: 10.90 },
    {   id: 3, 
        image: 'https://picsum.photos/id/495/800/600',
        title: 'Product 3',
        description: 'We focus on ergonomics and meeting you where you work. It\'s only a keystroke away.',
        date: '22 April 2021',
        comments: '10',
        price: 8.00 },
    {   id: 4, 
        image: 'https://picsum.photos/id/496/800/600',
        title: 'Product 4',
        description: 'We focus on ergonomics and meeting you where you work. It\'s only a keystroke away.',
        date: '22 April 2021',
        comments: '10',
        price: 10.00 
    },
    {   id: 5, 
        image: 'https://picsum.photos/id/497/800/600',
        title: 'Product 5',
        description: 'We focus on ergonomics and meeting you where you work. It\'s only a keystroke away.',
        date: '22 April 2021',
        comments: '10',
        price: 20.90 },
    {   id: 6, 
        image: 'https://picsum.photos/id/498/800/600',
        title: 'Product 6',
        description: 'We focus on ergonomics and meeting you where you work. It\'s only a keystroke away.',
        date: '22 April 2021',
        comments: '10',
        price: 10.90 },
    {   id: 7, 
        image: 'https://picsum.photos/id/695/800/600',
        title: 'Product 7',
        description: 'We focus on ergonomics and meeting you where you work. It\'s only a keystroke away.',
        date: '22 April 2021',
        comments: '10',
        price: 8.00 },
    {   id: 8, 
        image: 'https://picsum.photos/id/596/800/600',
        title: 'Product 8',
        description: 'We focus on ergonomics and meeting you where you work. It\'s only a keystroke away.',
        date: '22 April 2021',
        comments: '10',
        price: 10.00 
    },
];

export default mockData;